<a href="https://colab.research.google.com/github/yuta1105/test2/blob/master/%E6%A9%9F%E6%A2%B0%E5%AD%A6%E7%BF%92.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
1+2

3

In [0]:
(1+2*3-4)/5

0.6

In [0]:
2**8

256

In [0]:
x=1
y=1/3
x+y

1.3333333333333333

In [0]:
Date_1=1/5
Date_2=3/5
Date_1+Date_2

0.8

In [0]:
type(100)

int

In [0]:
type(100.1)

float

In [0]:
x=100
type(x)

int

In [0]:
x=100.1
type(x)

float

In [0]:
x='learning'
type(x)

str

In [0]:
x=1/3
x
y=2/3
y

0.6666666666666666

In [0]:
x=1/3
print(x)
y=2/3
print(y)

0.3333333333333333
0.6666666666666666


In [0]:
print('x='+str(x))

x=0.3333333333333333


In [0]:
print('weight={0}kg'.format(x))

weight=0.3333333333333333kg


In [0]:
x=1/3
y=1/7
z=1/4
print('weight:{0}kg,{1}kg,{2}kg'.format(x,y,z))

weight:0.3333333333333333kg,0.14285714285714285kg,0.25kg


In [0]:
print('weight:x={0:.2f}kg,y={1:.2f}kg,z={2:.2f}kg'.format(x,y,z))

weight:x=0.33kg,y=0.14kg,z=0.25kg


In [0]:
x=[1,1,2,3,5]#listの定義
print(x)#表示

[1, 1, 2, 3, 5]


In [0]:
x[0]

1

In [0]:
x[2]

2

In [0]:
print(type(x))
print(type(x[0]))

<class 'list'>
<class 'int'>


In [0]:
s=['SUN',1,'MON',2]
print(type(s[0]))
print(type(s[1]))

<class 'str'>
<class 'int'>


In [0]:
a=[[1,2,3],[4,5,6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [0]:
a=[[1,2,3],[4,5,6]]
print(a[0][1])

2


In [0]:
x=[1,1,2,3,5]
x[3]=100
print(x)

[1, 1, 2, 100, 5]


In [0]:
x=[1,1,2,3,5]
len(x)

5

In [0]:
y=range(5,10)
print(y[0],y[1],y[2],y[3],y[4])

5 6 7 8 9


In [0]:
print(y)

range(5, 10)


In [0]:
z=list(range(5,10))
print(z)

[5, 6, 7, 8, 9]


In [0]:
list(range(5,10))

[5, 6, 7, 8, 9]

In [0]:
a=(1,2,3)
print(a)

(1, 2, 3)


In [0]:
a[1]

2

In [0]:
type(a)

tuple

In [0]:
a=(1)
type(a)

int

In [0]:
a=(1,)
type(a)

tuple

In [0]:
x=11
if x>10:
  print('x is')#...(A1)
  print('     lager than 10.')#...(A2)
else:
  print('x is smaller than 11')#...(A3)


x is
     lager than 10.


In [0]:
x>10

True

In [0]:
type(x>10)

bool

In [0]:
x=15
if 10<=x and x<=20:
  print('x is between 10 and 20.')

x is between 10 and 20.


In [0]:
for i in [1,2,3]:
  print(i)

1
2
3


In [0]:
num=[2,4,6,8,10]
for i in range(len(num)):
  num[i]=num[i]*2
print(num)

[4, 8, 12, 16, 20]


In [0]:
num=[2,4,6,8,10]
for i,n in enumerate(num):
  num[i]=n*2
print(num)  

[4, 8, 12, 16, 20]


In [0]:
[1,2]+[3,4]

[1, 2, 3, 4]

In [0]:
import numpy as np

In [0]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [0]:
print(x)

[1 2 3]


In [0]:
y=np.array([4,5,6])
print(x+y)

[5 7 9]


In [0]:
type(x)

numpy.ndarray

In [0]:
x[0]

1

In [0]:
x[0]=100
print(x)

[100   2   3]


In [0]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [0]:
print(np.arange(5,10))

[5 6 7 8 9]


In [0]:
a=np.array([1,1])
b=a
print('a='+str(a))
print('b='+str(b))
b[0]=100
print('b='+str(b))
print('a='+str(a))

a=[1 1]
b=[1 1]
b=[100   1]
a=[100   1]


In [0]:
a=np.array([1,1])
b=a.copy()
print('a='+str(a))
print('b='+str(b))
b[0]=100
print('b='+str(b))
print('a='+str(a))

a=[1 1]
b=[1 1]
b=[100   1]
a=[1 1]


In [0]:
x=np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [0]:
x=np.array([[1,2,3],[4,5,6]])
x.shape

(2, 3)

In [0]:
w,h=x.shape
print(w)
print(h)

2
3


In [0]:
x=np.array([[1,2,3],[4,5,6]])
x[1,2]

6

In [0]:
x=np.array([[1,2,3],[4,5,6]])
x[1,2]=100
print(x)

[[  1   2   3]
 [  4   5 100]]


In [0]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [0]:
print(np.zeros((2,10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [0]:
print(np.ones((2,10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [2]:
np.random.rand(2,3)

array([[0.61729886, 0.39706972, 0.67766812],
       [0.76220701, 0.26921437, 0.29530838]])

In [4]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
x=np.array([[4,4,4],[8,8,8]])
y=np.array([[1,1,1],[2,2,2]])
print(x+y)

[[ 5  5  5]
 [10 10 10]]


In [8]:
x=np.array([[4,4,4],[8,8,8]])
print(10*x)

[[40 40 40]
 [80 80 80]]


In [9]:
x=np.array([[4,4,4],[8,8,8]])
print(np.exp(x))

[[  54.59815003   54.59815003   54.59815003]
 [2980.95798704 2980.95798704 2980.95798704]]


In [11]:
v=np.array([[1,2,3],[4,5,6]])
w=np.array([[1,1],[2,2],[3,3]])
print(v.dot(w))

[[14 14]
 [32 32]]


In [14]:
x=np.arange(10)
print(x)
print(x[:5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [15]:
print(x[5:])

[5 6 7 8 9]


In [16]:
print(x[3:8])

[3 4 5 6 7]


In [18]:
print(x[3:8:2])

[3 5 7]


In [19]:
print(x[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [20]:
y=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)
print(y[:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]]


In [21]:
x=np.array([1,1,2,3,5,8,13])
x>3

array([False, False, False, False,  True,  True,  True])

In [22]:
x[x>3]

array([ 5,  8, 13])

In [24]:
x[x>3]=999
print(x)

[  1   1   2   3 999 999 999]
