<a href="https://colab.research.google.com/github/yuta1105/test2/blob/master/%E8%B6%85AI%E5%85%A5%E9%96%80%E8%AC%9B%E5%BA%A7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
x = np.array([1,2])
x

array([1, 2])

In [4]:
w = np.array([[4,8],[6,3]])
w

array([[4, 8],
       [6, 3]])

In [5]:
x.dot(w)

array([16, 14])

In [6]:
a = np.array([1,4,7])
b = np.array([[2,8,7],[1,9,3],[6,4,0]])
a.dot(b)

array([48, 72, 19])

In [7]:
x = np.array([[4,5],[3,6]])
w = np.array([[7],[4]])
x.dot(w)

array([[48],
       [45]])